"""Policy-head targets generated by search.

This module is intentionally small: it gives training code a way to consume
solver/search-improved policy distributions without baking poker rules into the
network. The default trainer path does not use these targets unless explicitly
given a positive weight.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
import torch.optim as optim

from poker_ai.deep_cfr.networks import PolicyNetwork
from poker_ai.games.full_deck.state import N_ACTIONS, N_FEATURES


@dataclass(frozen=True)
class PolicyTargetBatch:
    features: torch.Tensor
    legal_masks: torch.Tensor
    target_probs: torch.Tensor
    weights: torch.Tensor


def _normalize_targets(
    target_probs: np.ndarray,
    legal_masks: np.ndarray,
) -> np.ndarray:
    legal = (legal_masks > 0).astype(np.float32)
    targets = np.asarray(target_probs, dtype=np.float32) * legal
    totals = targets.sum(axis=1, keepdims=True)
    legal_totals = legal.sum(axis=1, keepdims=True)
    fallback = legal / np.maximum(legal_totals, 1.0)
    return np.where(totals > 1e-8, targets / np.maximum(totals, 1e-8), fallback)


class PolicyTargetBuffer:
    """In-memory dataset of search-generated policy targets."""

    def __init__(
        self,
        features: np.ndarray,
        legal_masks: np.ndarray,
        target_probs: np.ndarray,
        weights: np.ndarray | None = None,
    ):
        features = np.asarray(features, dtype=np.float32)
        legal_masks = np.asarray(legal_masks, dtype=np.float32)
        target_probs = np.asarray(target_probs, dtype=np.float32)
        if features.ndim != 2 or features.shape[1] != N_FEATURES:
            raise ValueError(f"features must have shape (N, {N_FEATURES})")
        if legal_masks.shape != (features.shape[0], N_ACTIONS):
            raise ValueError(f"legal_masks must have shape (N, {N_ACTIONS})")
        if target_probs.shape != (features.shape[0], N_ACTIONS):
            raise ValueError(f"target_probs must have shape (N, {N_ACTIONS})")
        if np.any(legal_masks.sum(axis=1) <= 0):
            raise ValueError("each policy target needs at least one legal action")

        self.features = features
        self.legal_masks = (legal_masks > 0).astype(np.float32)
        self.target_probs = _normalize_targets(target_probs, self.legal_masks)
        if weights is None:
            self.weights = np.ones(features.shape[0], dtype=np.float32)
        else:
            weights = np.asarray(weights, dtype=np.float32)
            if weights.shape != (features.shape[0],):
                raise ValueError("weights must have shape (N,)")
            self.weights = weights
        self.size = int(features.shape[0])

    @classmethod
    def from_npz(cls, path: str | Path) -> "PolicyTargetBuffer":
        data = np.load(Path(path), allow_pickle=False)
        weights = data["weights"] if "weights" in data.files else None
        return cls(
            features=data["features"],
            legal_masks=data["legal_masks"],
            target_probs=data["target_probs"],
            weights=weights,
        )

    def save_npz(self, path: str | Path) -> None:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(
            path,
            features=self.features,
            legal_masks=self.legal_masks,
            target_probs=self.target_probs,
            weights=self.weights,
        )

    def sample_batch(
        self,
        batch_size: int,
        device: torch.device | None = None,
    ) -> PolicyTargetBatch:
        if self.size <= 0:
            raise ValueError("empty policy target buffer")
        n = min(int(batch_size), self.size)
        indices = np.random.randint(0, self.size, size=n)
        features = torch.from_numpy(self.features[indices])
        legal_masks = torch.from_numpy(self.legal_masks[indices])
        target_probs = torch.from_numpy(self.target_probs[indices])
        weights = torch.from_numpy(self.weights[indices])
        if device is not None:
            features = features.to(device)
            legal_masks = legal_masks.to(device)
            target_probs = target_probs.to(device)
            weights = weights.to(device)
        return PolicyTargetBatch(features, legal_masks, target_probs, weights)


class MixedPolicyTargetBuffer:
    """Sample from several policy-target buffers as one training source."""

    def __init__(
        self,
        *buffers: PolicyTargetBuffer | "PolicyReservoirBuffer" | None,
    ):
        self.buffers = [
            buffer for buffer in buffers if buffer is not None and int(buffer.size) > 0
        ]
        if not self.buffers:
            raise ValueError("MixedPolicyTargetBuffer needs at least one non-empty buffer")
        self.size = int(sum(int(buffer.size) for buffer in self.buffers))

    def sample_batch(
        self,
        batch_size: int,
        device: torch.device | None = None,
    ) -> PolicyTargetBatch:
        n = min(int(batch_size), self.size)
        if n <= 0:
            raise ValueError("empty mixed policy target buffer")
        sizes = np.asarray(
            [int(buffer.size) for buffer in self.buffers],
            dtype=np.float64,
        )
        expected = n * sizes / sizes.sum()
        counts = np.floor(expected).astype(np.int64)
        remainder = int(n - counts.sum())
        if remainder > 0:
            order = np.argsort(-(expected - counts))
            for idx in order[:remainder]:
                counts[int(idx)] += 1
        batches = [
            buffer.sample_batch(int(count), device=None)
            for buffer, count in zip(self.buffers, counts, strict=True)
            if int(count) > 0
        ]
        features = torch.cat([batch.features for batch in batches], dim=0)
        legal_masks = torch.cat([batch.legal_masks for batch in batches], dim=0)
        target_probs = torch.cat([batch.target_probs for batch in batches], dim=0)
        weights = torch.cat([batch.weights for batch in batches], dim=0)
        if device is not None:
            features = features.to(device)
            legal_masks = legal_masks.to(device)
            target_probs = target_probs.to(device)
            weights = weights.to(device)
        return PolicyTargetBatch(features, legal_masks, target_probs, weights)


def policy_target_calibration_metadata(
    target_buffer: PolicyTargetBuffer | None,
    *,
    weight: float,
    source: str | None = None,
) -> dict:
    """Return checkpoint metadata for policy heads trained from search targets."""
    if (
        target_buffer is None
        or float(weight) <= 0.0
        or getattr(target_buffer, "size", 0) <= 0
    ):
        return {}
    street_one_hot = np.asarray(target_buffer.features, dtype=np.float32)[:, 104:108]
    valid = np.max(street_one_hot, axis=1) > 0
    streets = np.argmax(street_one_hot, axis=1)[valid].astype(np.int64)
    unique, counts = np.unique(streets, return_counts=True)
    metadata = {
        "source": "search_targets",
        "target_size": int(target_buffer.size),
        "search_target_weight": float(weight),
        "target_streets": [int(street) for street in unique],
        "target_street_counts": {
            str(int(street)): int(count)
            for street, count in zip(unique, counts, strict=True)
        },
    }
    if source:
        metadata["source_targets"] = str(source)
    return metadata


class PolicyReservoirBuffer:
    """Reservoir-sampled mutable policy-target memory."""

    def __init__(self, capacity: int = 2_000_000):
        self.capacity = int(capacity)
        self.features = np.zeros((self.capacity, N_FEATURES), dtype=np.float32)
        self.legal_masks = np.zeros((self.capacity, N_ACTIONS), dtype=np.float32)
        self.target_probs = np.zeros((self.capacity, N_ACTIONS), dtype=np.float32)
        self.weights = np.zeros(self.capacity, dtype=np.float32)
        self.size = 0
        self._n_seen = 0

    def add(
        self,
        features: np.ndarray,
        legal_mask: np.ndarray,
        target_probs: np.ndarray,
        weight: float = 1.0,
    ) -> None:
        self.add_batch(
            np.asarray(features, dtype=np.float32).reshape(1, N_FEATURES),
            np.asarray(legal_mask, dtype=np.float32).reshape(1, N_ACTIONS),
            np.asarray(target_probs, dtype=np.float32).reshape(1, N_ACTIONS),
            np.asarray([weight], dtype=np.float32),
            1,
        )

    def add_batch(
        self,
        features_batch: np.ndarray,
        legal_masks_batch: np.ndarray,
        target_probs_batch: np.ndarray,
        weights_batch: np.ndarray | float,
        count: int,
    ) -> None:
        count = int(count)
        if count <= 0:
            return
        features_batch = np.asarray(features_batch[:count], dtype=np.float32)
        legal_masks_batch = (np.asarray(legal_masks_batch[:count], dtype=np.float32) > 0).astype(
            np.float32
        )
        target_probs_batch = _normalize_targets(
            np.asarray(target_probs_batch[:count], dtype=np.float32),
            legal_masks_batch,
        )
        if np.isscalar(weights_batch):
            weights = np.full(count, float(weights_batch), dtype=np.float32)
        else:
            weights = np.asarray(weights_batch[:count], dtype=np.float32)
        if features_batch.shape != (count, N_FEATURES):
            raise ValueError(f"features_batch must have shape ({count}, {N_FEATURES})")
        if legal_masks_batch.shape != (count, N_ACTIONS):
            raise ValueError(f"legal_masks_batch must have shape ({count}, {N_ACTIONS})")
        if target_probs_batch.shape != (count, N_ACTIONS):
            raise ValueError(f"target_probs_batch must have shape ({count}, {N_ACTIONS})")
        if weights.shape != (count,):
            raise ValueError(f"weights_batch must have shape ({count},)")
        if np.any(legal_masks_batch.sum(axis=1) <= 0):
            raise ValueError("each policy target needs at least one legal action")

        n_direct = 0
        if self.size < self.capacity:
            n_direct = min(count, self.capacity - self.size)
            start = self.size
            end = start + n_direct
            self.features[start:end] = features_batch[:n_direct]
            self.legal_masks[start:end] = legal_masks_batch[:n_direct]
            self.target_probs[start:end] = target_probs_batch[:n_direct]
            self.weights[start:end] = weights[:n_direct]
            self.size += n_direct
            self._n_seen += n_direct

        n_reservoir = count - n_direct
        if n_reservoir > 0:
            n_seen_base = self._n_seen
            n_seen_values = n_seen_base + np.arange(1, n_reservoir + 1)
            rand_idx = (np.random.random(n_reservoir) * n_seen_values).astype(np.int64)
            keep_positions = np.where(rand_idx < self.capacity)[0]
            if keep_positions.size:
                src_indices = n_direct + keep_positions
                dst_indices = rand_idx[keep_positions]
                self.features[dst_indices] = features_batch[src_indices]
                self.legal_masks[dst_indices] = legal_masks_batch[src_indices]
                self.target_probs[dst_indices] = target_probs_batch[src_indices]
                self.weights[dst_indices] = weights[src_indices]
            self._n_seen += n_reservoir

    def sample_batch(
        self,
        batch_size: int,
        device: torch.device | None = None,
    ) -> PolicyTargetBatch:
        if self.size <= 0:
            raise ValueError("empty policy target reservoir")
        n = min(int(batch_size), self.size)
        indices = np.random.randint(0, self.size, size=n)
        batch = PolicyTargetBatch(
            features=torch.from_numpy(self.features[indices]),
            legal_masks=torch.from_numpy(self.legal_masks[indices]),
            target_probs=torch.from_numpy(self.target_probs[indices]),
            weights=torch.from_numpy(self.weights[indices]),
        )
        if device is None:
            return batch
        return PolicyTargetBatch(
            features=batch.features.to(device),
            legal_masks=batch.legal_masks.to(device),
            target_probs=batch.target_probs.to(device),
            weights=batch.weights.to(device),
        )

    def to_policy_target_buffer(self) -> PolicyTargetBuffer:
        return PolicyTargetBuffer(
            self.features[:self.size],
            self.legal_masks[:self.size],
            self.target_probs[:self.size],
            self.weights[:self.size],
        )

    def __len__(self) -> int:
        return self.size


def masked_policy_cross_entropy(
    logits: torch.Tensor,
    legal_masks: torch.Tensor,
    target_probs: torch.Tensor,
    weights: torch.Tensor | None = None,
) -> torch.Tensor:
    """Cross entropy from logits to legal, normalized policy targets."""
    legal_masks = (legal_masks > 0).to(dtype=logits.dtype)
    target_probs = target_probs.to(dtype=logits.dtype) * legal_masks
    totals = target_probs.sum(dim=1, keepdim=True)
    legal_totals = legal_masks.sum(dim=1, keepdim=True).clamp(min=1.0)
    fallback = legal_masks / legal_totals
    target_probs = torch.where(
        totals > 1e-8,
        target_probs / totals.clamp(min=1e-8),
        fallback,
    )
    masked_logits = logits.masked_fill(legal_masks <= 0, -1e4)
    per_sample = -(target_probs * torch.log_softmax(masked_logits, dim=1)).sum(dim=1)
    if weights is None:
        return per_sample.mean()
    weights = weights.to(dtype=per_sample.dtype).clamp(min=0)
    return (per_sample * weights).sum() / weights.sum().clamp(min=1e-8)


def train_average_policy_network(
    strategy_buffer: PolicyTargetBuffer | PolicyReservoirBuffer,
    *,
    hidden_dim: int = 256,
    n_layers: int = 2,
    n_epochs: int = 1000,
    batch_size: int = 2048,
    lr: float = 0.001,
    device: torch.device | None = None,
    use_betting_history: bool = True,
) -> PolicyNetwork:
    """Train a standalone average-strategy network from strategy memory."""
    if getattr(strategy_buffer, "size", 0) <= 0:
        raise ValueError("strategy_buffer must contain policy targets")
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    net = PolicyNetwork(
        N_FEATURES,
        hidden_dim=hidden_dim,
        output_dim=N_ACTIONS,
        n_layers=n_layers,
        use_betting_history=use_betting_history,
    ).to(device)
    optimizer = optim.Adam(net.parameters(), lr=lr)
    net.train()

    for _ in range(max(1, int(n_epochs))):
        batch = strategy_buffer.sample_batch(batch_size, device)
        optimizer.zero_grad(set_to_none=True)
        logits = net(batch.features)
        loss = masked_policy_cross_entropy(
            logits,
            batch.legal_masks,
            batch.target_probs,
            weights=batch.weights,
        )
        loss.backward()
        optimizer.step()

    net.eval()
    return net
