"""Policy-head targets generated by search.

This module is intentionally small: it gives training code a way to consume
solver/search-improved policy distributions without baking poker rules into the
network. The default trainer path does not use these targets unless explicitly
given a positive weight.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch

from poker_ai.games.full_deck.state import N_ACTIONS, N_FEATURES


@dataclass(frozen=True)
class PolicyTargetBatch:
    features: torch.Tensor
    legal_masks: torch.Tensor
    target_probs: torch.Tensor
    weights: torch.Tensor


def _normalize_targets(
    target_probs: np.ndarray,
    legal_masks: np.ndarray,
) -> np.ndarray:
    legal = (legal_masks > 0).astype(np.float32)
    targets = np.asarray(target_probs, dtype=np.float32) * legal
    totals = targets.sum(axis=1, keepdims=True)
    legal_totals = legal.sum(axis=1, keepdims=True)
    fallback = legal / np.maximum(legal_totals, 1.0)
    return np.where(totals > 1e-8, targets / np.maximum(totals, 1e-8), fallback)


class PolicyTargetBuffer:
    """In-memory dataset of search-generated policy targets."""

    def __init__(
        self,
        features: np.ndarray,
        legal_masks: np.ndarray,
        target_probs: np.ndarray,
        weights: np.ndarray | None = None,
    ):
        features = np.asarray(features, dtype=np.float32)
        legal_masks = np.asarray(legal_masks, dtype=np.float32)
        target_probs = np.asarray(target_probs, dtype=np.float32)
        if features.ndim != 2 or features.shape[1] != N_FEATURES:
            raise ValueError(f"features must have shape (N, {N_FEATURES})")
        if legal_masks.shape != (features.shape[0], N_ACTIONS):
            raise ValueError(f"legal_masks must have shape (N, {N_ACTIONS})")
        if target_probs.shape != (features.shape[0], N_ACTIONS):
            raise ValueError(f"target_probs must have shape (N, {N_ACTIONS})")
        if np.any(legal_masks.sum(axis=1) <= 0):
            raise ValueError("each policy target needs at least one legal action")

        self.features = features
        self.legal_masks = (legal_masks > 0).astype(np.float32)
        self.target_probs = _normalize_targets(target_probs, self.legal_masks)
        if weights is None:
            self.weights = np.ones(features.shape[0], dtype=np.float32)
        else:
            weights = np.asarray(weights, dtype=np.float32)
            if weights.shape != (features.shape[0],):
                raise ValueError("weights must have shape (N,)")
            self.weights = weights
        self.size = int(features.shape[0])

    @classmethod
    def from_npz(cls, path: str | Path) -> "PolicyTargetBuffer":
        data = np.load(Path(path), allow_pickle=False)
        weights = data["weights"] if "weights" in data.files else None
        return cls(
            features=data["features"],
            legal_masks=data["legal_masks"],
            target_probs=data["target_probs"],
            weights=weights,
        )

    def save_npz(self, path: str | Path) -> None:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(
            path,
            features=self.features,
            legal_masks=self.legal_masks,
            target_probs=self.target_probs,
            weights=self.weights,
        )

    def sample_batch(
        self,
        batch_size: int,
        device: torch.device | None = None,
    ) -> PolicyTargetBatch:
        if self.size <= 0:
            raise ValueError("empty policy target buffer")
        n = min(int(batch_size), self.size)
        indices = np.random.randint(0, self.size, size=n)
        features = torch.from_numpy(self.features[indices])
        legal_masks = torch.from_numpy(self.legal_masks[indices])
        target_probs = torch.from_numpy(self.target_probs[indices])
        weights = torch.from_numpy(self.weights[indices])
        if device is not None:
            features = features.to(device)
            legal_masks = legal_masks.to(device)
            target_probs = target_probs.to(device)
            weights = weights.to(device)
        return PolicyTargetBatch(features, legal_masks, target_probs, weights)


def masked_policy_cross_entropy(
    logits: torch.Tensor,
    legal_masks: torch.Tensor,
    target_probs: torch.Tensor,
    weights: torch.Tensor | None = None,
) -> torch.Tensor:
    """Cross entropy from logits to legal, normalized policy targets."""
    legal_masks = (legal_masks > 0).to(dtype=logits.dtype)
    target_probs = target_probs.to(dtype=logits.dtype) * legal_masks
    totals = target_probs.sum(dim=1, keepdim=True)
    legal_totals = legal_masks.sum(dim=1, keepdim=True).clamp(min=1.0)
    fallback = legal_masks / legal_totals
    target_probs = torch.where(
        totals > 1e-8,
        target_probs / totals.clamp(min=1e-8),
        fallback,
    )
    masked_logits = logits.masked_fill(legal_masks <= 0, -1e4)
    per_sample = -(target_probs * torch.log_softmax(masked_logits, dim=1)).sum(dim=1)
    if weights is None:
        return per_sample.mean()
    weights = weights.to(dtype=per_sample.dtype).clamp(min=0)
    return (per_sample * weights).sum() / weights.sum().clamp(min=1e-8)
